#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: AirSonos
# Runs the AirSonos server
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

hass.log.info 'Starting the deCONZ server'

# Non-interactive
options+=(-platform minimal)

# Connect to zigbee adapter
options+=(--auto-connect=1)

options+=(--dbg-info=1)

# Bind to a specific interface
if hass.config.has_value 'httpport'; then
    options+=("--http-port=$(hass.config.get 'httpport')")
fi
if hass.config.has_value 'wsport'; then
    options+=("--ws-port=$(hass.config.get 'wsport')")
fi

# Run deCONZ
exec deCONZ "${options[@]}"
